### ISSUE TITLE
Difficult to import in browser due to dependencies using node built-in modules like process.

### ISSUE THREAD

**Issue by Leftium** [StefanTerdell/json-schema-to-zod#29]
Would it be possible to remove the dependencies that use node built-in modules like `process`?

Simply importing `json-schema-to-zod` results in an error:
<pre>
ReferenceError: process is not defined
    at node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/util/url.js (url.js:3:29)
    at __require (chunk-J43GMYXM.js?v=f53e2eac:11:50)
    at node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/pointer.js (pointer.js:6:13)
    at __require (chunk-J43GMYXM.js?v=f53e2eac:11:50)
    at node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/ref.js (ref.js:5:17)
    at __require (chunk-J43GMYXM.js?v=f53e2eac:11:50)
    at node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/refs.js (refs.js:4:14)
    at __require (chunk-J43GMYXM.js?v=f53e2eac:11:50)
    at node_modules/.pnpm/@apidevtools+json-schema-ref-parser@9.0.9/node_modules/@apidevtools/json-schema-ref-parser/lib/index.js (index.js:4:15)
    at __require (chunk-J43GMYXM.js?v=f53e2eac:11:50)
</pre>

This is because some dependency is checking the platform via `process`:

    // url.js
    let isWindows = /^win/.test(process.platform),

I was able to get `json-schema-to-zod` working in Parcel via its [node emulation](https://parceljs.org/features/node-emulation/#polyfilling-%26-excluding-builtin-node-modules), but it required some extra steps: https://github.com/parcel-bundler/parcel/issues/7697#issuecomment-1360074613

I was unable to get similar node emulation working in SvelteKit/Vite. Perhaps because the dependencies don't explicitly import `process` so Parcel is doing some extra magic.

I am curious how the online demo (https://stefanterdell.github.io/json-schema-to-zod-react/) does not result in the same error. Does this also use node emulation, or was it built with versions of dependencies that didn't use `process`?

**Comment by StefanTerdell** [comment]
I made my own synchronous ref parser a while ago with zero dependencies. I'll get that ready for the big stage and use that instead. It may take a while since I'm pretty swamped at work still, so if it's time sensitive I suggest you make your own fork in the meantime.

**Comment by Leftium** [comment]
Cool, I can just use my workaround in the meantime.

**Comment by Marviel** [comment]
@StefanTerdell hey Stefan, could you post what you have? I'd be happy to try to take up the torch from there.

**Comment by magick93** [comment]
I found adding the following to my `vite.config.ts` solved the problem:

```
...
define: {
		'process.env': {}
	  }
```

**Comment by StefanTerdell** [comment]
Got rid of the offending dependency in 1.0.0

**Comment by StefanTerdell** [comment]
Ugh nevermind that somehow made it worse. The best solution would probably be to just split the CLI (along with the ref resolver) and the transformer into two separate packages, possibly converting this repo into a monorepo in the process. Then we could chuck the playground app in here as well. But honestly I just can't fathom why people want to use this at runtime in the first place so I'm just going to ignore this for now. The playground app uses webpack 4.* so it's polyfilled by default. If anyone else wants to take a stab at it feel free to do so, but I can't really be bothered, sorry 😓

**Comment by StefanTerdell** [comment]
"Fixed" in v2: I removed ref parsing. And prettier. Kthxbye :D
