### ISSUE TITLE
Doesn't like double quotes in descriptions (does this produce extremely insecure code?)

### ISSUE THREAD

**Issue by LukasDoesDev** [StefanTerdell/json-schema-to-zod#5]
Example:
```sh
echo '{"title": "Foo Bar", "type": "string", "description": "\"\" means the default."}' | json-schema-to-zod -s /dev/stdin
```

**Comment by LukasDoesDev** [comment]
Returns with the following error printed to stdout
```
Failed to parse sourcefile content to Zod schema
SyntaxError: Unexpected token, expected "," (1:36)
> 1 | const schema=z.string().describe(""" means the default.")
    |                                    ^
    at p (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/parser-babel.js:22:1038)
    at d (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/parser-babel.js:22:1271)
    at Object.parse (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/parser-babel.js:27:50335)
    at Object.parse (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/index.js:7361:23)
    at coreFormat (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/index.js:8672:18)
    at formatWithCursor2 (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/index.js:8864:18)
    at /home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/index.js:39174:12
    at Object.format (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/node_modules/prettier/index.js:39188:12)
    at format (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/utils/format.js:9:47)
    at jsonSchemaToZod (/home/luukas/.local/share/fnm/node-versions/v17.5.0/installation/lib/node_modules/json-schema-to-zod/jsonSchemaToZod.js:14:78) {
  loc: { start: { line: 1, column: 36 } },
  codeFrame: '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m 1 |\x1B[39m \x1B[36mconst\x1B[39m schema\x1B[33m=\x1B[39mz\x1B[33m.\x1B[39mstring()\x1B[33m.\x1B[39mdescribe(\x1B[32m""\x1B[39m\x1B[32m" means the default."\x1B[39m)\x1B[0m\n' +
    '\x1B[0m \x1B[90m   |\x1B[39m                                    \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m'
}
```

**Comment by LukasDoesDev** [comment]
Ok this **is** extremely insecure:
https://github.com/StefanTerdell/json-schema-to-zod/blob/142dcb9b9243151bc1fd582915c674e1c0f45478/src/parsers/parseSchema.ts#L30-L33=

**Comment by StefanTerdell** [comment]
PR welcomed

**Comment by StefanTerdell** [comment]
Adressed in 0.1.2
