### ISSUE TITLE
Invalid published directory structure

### ISSUE THREAD

**Issue by gjuchault** [StefanTerdell/json-schema-to-zod#9]
Hello

It seems that on version 0.1.4, the content of the published tarball is invalid:
<img width="818" alt="image" src="https://user-images.githubusercontent.com/678848/183251643-09d3ccd9-cf8f-44fe-9bdf-3d35d8c5d1d6.png">

Which is causing the following error:
```
> require('json-schema-to-zod');
Uncaught:
Error: Cannot find module '/some/path/node_modules/json-schema-to-zod/index.js'. Please verify that the package.json has a valid "main" entry
```

Link to the tarball: https://registry.npmjs.org/json-schema-to-zod/-/json-schema-to-zod-0.1.4.tgz

**Comment by StefanTerdell** [comment]
Thanks @gjuchault! Fixed with 0.1.5

**Comment by bryanhelmig** [comment]
Seems like this is happening on 0.3.0 again?

```
yarn run v1.22.18
$ bin/generate
Error: Cannot find module '/Users/bryanhelmig/code/zod-project/node_modules/json-schema-to-zod/index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (node:internal/modules/cjs/loader:353:19)
    at Function.Module._findPath (node:internal/modules/cjs/loader:566:18)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._resolveFilename.sharedData.moduleResolveFilenameHook.installedValue [as _resolveFilename] (/Users/bryanhelmig/code/zod-project/node_modules/@cspotcode/source-map-support/source-map-support.js:811:30)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/bryanhelmig/code/zod-project/bin/zodify.ts:4:13)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
    at Module.m._compile (/Users/bryanhelmig/code/zod-project/node_modules/ts-node/src/index.ts:1618:23) {
  code: 'MODULE_NOT_FOUND',
  path: '/Users/bryanhelmig/code/zod-project/node_modules/json-schema-to-zod/package.json',
  requestPath: 'json-schema-to-zod'
}
```

**Comment by bryanhelmig** [comment]
0.2.0 confirmed to work.
